# Configuración de la aplicación
spring.application.name=consulta-ms
server.port=8080

# Configuración de la base de datos
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=TOL
spring.datasource.password=admin123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect